{% set version = "0.6-17" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lavaan
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lavaan_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lavaan/lavaan_{{ version }}.tar.gz
  sha256: 9233251e32ccfba49928ea8320a28e65fdd423bddf44e63622b08c75c25ef7ae

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-mnormt
    - r-numderiv
    - r-pbivnorm
    - r-quadprog
  run:
    - r-base
    - r-mass
    - r-mnormt
    - r-numderiv
    - r-pbivnorm
    - r-quadprog

test:
  commands:
    - $R -e "library('lavaan')"           # [not win]
    - "\"%R%\" -e \"library('lavaan')\""  # [win]

about:
  home: https://lavaan.ugent.be
  dev_url: https://github.com/yrosseel/lavaan
  license: GPL-2.0-or-later
  summary: Fit a variety of latent variable models, including confirmatory factor analysis, structural equation modeling and latent growth curve models.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
