{% set version = "0.6-19" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-lavaan
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lavaan_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lavaan/lavaan_{{ version }}.tar.gz
  sha256: 47b137e3c164d33a433698bd5da82157cc8d9bfa8b04711d10a1745a57e8b785

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-mnormt
    - r-numderiv
    - r-pbivnorm
    - r-quadprog
  run:
    - r-base
    - r-mass
    - r-mnormt
    - r-numderiv
    - r-pbivnorm
    - r-quadprog

test:
  commands:
    - $R -e "library('lavaan')"           # [not win]
    - "\"%R%\" -e \"library('lavaan')\""  # [win]

about:
  home: https://lavaan.ugent.be
  dev_url: https://github.com/yrosseel/lavaan
  license: GPL-2.0-or-later
  summary: Fit a variety of latent variable models, including confirmatory factor analysis, structural equation modeling and latent growth curve models.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
