travis:
  secure:
    BINSTAR_TOKEN: D1sVMUQwrDgdF7EJZZ8nppB5SYMKSkbWb0An8MCK4J0XVEVCt5adlettSOx7iw+pQa+rr69dayRMws+RR8RbVWhrurSr/QZqBdi8Wr0iok6iJCrJNXvPqvBaQLSpnzcfujK+Fds1oOnjBXGQFCX/D5l4NaZWc2gxD9sWEgpe0tK2Q2SV9SdiTy4lOaVe8HL6Y8/rVl2N+IRrjbd106Wb+nYIQsgd6l1kBTE+Kk/7ualOxIkDfK1RcDSFe0gltEE7zMU7EoDYsxJkubwHaoMpP19MsawmQVLHb6tIddvBEpXREdE5xG9FeSc5VYeqvxRTsVRXFly72hTegWanPOp03+0GwnmcHCCHw2BTOlh5hqS8x8ShOwSWSwXhcP+GQqLQ4W8VA/dLPZjpgEAcl68AU5xITzGQJVcTzOdxJe7AYBh6eNx6levwgPc7GKFl/NEqZxxrvdG/iPQwL7zNudJLytlT9tGhDtJX0TLFv+G49gxoAVXXBp8tx8Str2MW2Lj5SNtjViIqOneM3iRfcYdeBiElAcaTQSPuYQOM5KYRejrtVKAXzu2Sz+GxlkaTSk+s1ifKcvT00TddyXLMUqq66Np+sCSoT0TTM6ztC02d65ecFP54JKDDREWlwBhhMPnbvQdQfGSCyvInKh6An0iEyweglNzGSqQ6DyuAtsFdrj0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
